### ISSUE TITLE
需要对生成对箱形图数据进行对比

### ISSUE THREAD

**Issue by XinYueXiao** [alitajs/rc-charts#13]
单个箱形图数据显示，箱形图和箱形图之间对比

**Comment by XinYueXiao** [comment]
![image](https://user-images.githubusercontent.com/31272499/60694136-a7336580-9f0f-11e9-9be5-8769849eba22.png)
这个样子

**Comment by wangxingkang** [comment]
好的，我们调研一下

**Comment by xiaohuoni** [comment]
@XinYueXiao 这个图怎么出来的，欢迎PR
