### ISSUE TITLE
根据数据在图标里加一个平均数据辅助线

### ISSUE THREAD

**Issue by XinYueXiao** [alitajs/rc-charts#14]
![image](https://user-images.githubusercontent.com/31272499/60696580-edd98d80-9f18-11e9-953b-2ff7f967b80c.png)

**Comment by wangxingkang** [comment]
已添加 https://github.com/alitajs/rc-charts/commit/0e0de4d7bbf65b00e9edb4ac85fa4c682aabbe66

**Comment by wangxingkang** [comment]
会随下个版本发布

**Comment by xiaohuoni** [comment]
👍
