### ISSUE TITLE
pie 显示详细图例  legend click无效

### ISSUE THREAD

**Issue by NsNe** [alitajs/rc-charts#22]
问题如题，实例如下：
https://alitajs.github.io/rc-charts/pie#%E6%98%BE%E7%A4%BA%E8%AF%A6%E7%BB%86%E5%9B%BE%E4%BE%8B

**Comment by NsNe** [comment]
另外，示例网站，刷新404，应该用的browserRouter，服务器没有添加对应配置

**Comment by wangxingkang** [comment]
谢谢反馈  会尽快修复
